"""add tracks to student

Revision ID: 2cb1e9c3813c
Revises: 54d4f5ba220b
Create Date: 2024-02-21 09:52:29.258586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb1e9c3813c'
down_revision = '54d4f5ba220b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('track')

    # ### end Alembic commands ###
