"""create tracks table

Revision ID: 500fac0d9c4b
Revises: ef64d6d804cd
Create Date: 2024-02-21 09:25:36.676074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500fac0d9c4b'
down_revision = 'ef64d6d804cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    # ### end Alembic commands ###
