"""remove track

Revision ID: a893074db243
Revises: 2cb1e9c3813c
Create Date: 2024-02-21 09:54:32.553919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a893074db243'
down_revision = '2cb1e9c3813c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('track')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
